# Generated by Django 5.0.6 on 2024-07-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
            ],
        ),
    ]
