# Generated by Django 5.0.6 on 2024-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cart_caddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='caddress',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='caddress',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
