# Generated by Django 5.0.6 on 2024-07-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_cart_caddress_orderdetail_caddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='caddress',
        ),
        migrations.AddField(
            model_name='customer_registration',
            name='address',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
