# Generated by Django 5.0.6 on 2024-07-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_orderdetail_caddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
