# Generated by Django 5.0.6 on 2024-07-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_delete_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dish_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cart'),
        ),
    ]
