# Generated by Django 5.0.6 on 2024-07-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_order_dish_detail'),
        ('restaurant', '0002_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dishes')),
            ],
        ),
    ]
