# Generated by Django 5.0.6 on 2024-07-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Order',
            new_name='order',
        ),
    ]
