# Generated by Django 5.0.6 on 2024-07-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_order_orderdetail_order'),
        ('restaurant', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant_reg'),
        ),
    ]
