# Generated by Django 5.0.6 on 2024-07-14 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_order_restaurant_detail'),
        ('restaurant', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant_reg'),
        ),
    ]
