# Generated by Django 5.0.6 on 2024-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.TextField(max_length=100, null=True)),
                ('restphone', models.TextField(max_length=100, null=True)),
                ('restaddress', models.TextField(max_length=100, null=True)),
                ('restemail', models.TextField(max_length=100, null=True)),
                ('restpassword', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
