# Generated by Django 5.0.6 on 2024-07-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.TextField(max_length=100, null=True)),
                ('ddiscription', models.TextField(max_length=500, null=True)),
                ('dprice', models.FloatField(null=True)),
                ('dimage', models.ImageField(null=True, upload_to='dishes')),
                ('drestaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant_reg')),
            ],
        ),
    ]
